# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Bun CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on:
      ubuntu-latest
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      # - run: bun ci
      - run: bun run build
      - run: bun test
      - name: Deploy on Cloud:
        - run: curl "https://api.render.com/deploy/srv-crmts8l6l47c73fucdng?key=gjX24k3h4pU"